# Finding Principal Stresses and Directions

This notebooks shows how you use eigenvalue computations to determine the principal stresses and directions for an example state of stress at a point.

First import a number of functions from NumPy that will be useful. The most important is te `eig` function which will compute the eigenvalues and eigenvectors.

In [1]:
from numpy import array, pi, dot, sqrt, arccos, rad2deg
from numpy.linalg import eig

We will use the stress tensor we found in the multi-axial stress example in lecture 8. First define some values for the geometry and the applied load.

In [2]:
D = 0.5  # in
d = 0.25  # in
a = 5  # in
b = 4  # in
P = 10  # lb

The max bending and torsional stresses act at a distance $r$ from the neutral axis.

In [3]:
r = D / 2
r

0.25

The second moment of area and polar second moment of area of a tubular cross section is:

In [4]:
I = pi / 64 * (D**4 - d**4)
I

0.002876213977285577

In [5]:
J = pi / 32 * (D**4 - d**4)
J

0.005752427954571154

Now form the Cauchy Stress Tensor:

$$
\sigma =
\begin{bmatrix}
0 & 0 & \frac{Pbr}{J} \\
0 & 0 & 0 \\
\frac{Pbr}{J} & 0 & \frac{Par}{I}
\end{bmatrix}
$$

In [6]:
sigma = array([[0,             0, P * b * r / J],
               [0,             0, 0            ],
               [P * b * r / J, 0, P * a * r / I]])
sigma

array([[    0.        ,     0.        ,  1738.39639175],
       [    0.        ,     0.        ,     0.        ],
       [ 1738.39639175,     0.        ,  4345.99097936]])

Now we can use the `eig` function to find the principal stresses (eigenvalues) and principal directions (eigenvectors) of the stress tensor.

In [7]:
eig?

In [8]:
evals, evecs = eig(sigma)

The eigenvalues are given in arbitrary order, but each value corresponds to the column in the eigenvector array where both follow the same order.

In [9]:
evals

array([ -609.79652788,  4955.78750724,     0.        ])

In [10]:
evecs

array([[-0.94362832, -0.33100694,  0.        ],
       [ 0.        ,  0.        ,  1.        ],
       [ 0.33100694, -0.94362832,  0.        ]])

Note that the eigenvectors are of unit length. For example, the magnitude of the first eigenvector is:

In [11]:
sqrt(sum(evecs[:, 0]**2))

0.99999999999999989

Note also that we have one zero eigenvalue that corresponds to the $y$ axis. This indicates that we have planar stress in the $xz$ plane.

The angle of the principal direction vector $\hat{\mathbf{v}}$ with respect to the $\hat{\mathbf{x}}$ unit vector can be found using:

$$
\theta = \arccos{\hat{\mathbf{v}} \cdot \hat{\mathbf{x}}}
$$

In [12]:
xhat = array([1, 0, 0])
v3 = evecs[:, 0]
theta3 = arccos(dot(v3, xhat))
rad2deg(theta3)

160.67009587295496

In [13]:
xhat = array([1, 0, 0])
v1 = evecs[:, 1]
theta1 = 2 * pi - arccos(dot(v1, xhat))
rad2deg(theta1)

250.67009587295496

The principal directions should be orthogonal, i.e. $90^\circ$ apart.

In [14]:
rad2deg(theta1) - rad2deg(theta3)

90.0